site_title = "BioArxiv"
limit_days = 7
cache_url = "https://erosminer.github.io/MyArxiv/cache.json"

[[sources]]
limit = 150
category = "q-bio.GN"
title = "Genomics"

[[sources]]
limit = 150
category = "q-bio.MN"
title = "Molecular Networks"

[[sources]]
limit = 150
category = "q-bio.PE"
title = "Populations and Evolution"

[[sources]]
limit = 150
category = "q-bio.QM"
title = "Quantitative Methods"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
